name    'netmanagers-java'
version '1.0.0'
author  'Javier Bertoli'
license 'Apache2'
project_page 'http://www.netmanagers.com.ar'
source  'https://github.com/netmanagers/puppet-java'
summary 'Puppet module for java'
description 'This module installs and manages java. Check README for details.'
dependency 'example42/puppi', '>= 2.0.0'
